package kiki.gui;

import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/**
 * A chat bubble containing one message and a simple speaker badge.
 */
public class DialogBox extends HBox {
    private final Label text;
    private final Label avatar;

    private DialogBox(String message, String speaker, String styleClass) {
        text = new Label(message);
        avatar = new Label(speaker);

        text.setWrapText(true);
        text.getStyleClass().add("message-bubble");
        avatar.getStyleClass().addAll("avatar", styleClass);
        setSpacing(10);
        getChildren().addAll(avatar, text);
    }

    /**
     * Creates a dialog box for the user's message.
     *
     * @param message Message typed by the user.
     * @return A right-aligned user dialog box.
     */
    public static DialogBox getUserDialog(String message) {
        DialogBox dialogBox = new DialogBox(message, "You", "user-avatar");
        dialogBox.setAlignment(Pos.TOP_RIGHT);
        dialogBox.getChildren().setAll(dialogBox.text, dialogBox.avatar);
        HBox.setHgrow(dialogBox.text, javafx.scene.layout.Priority.ALWAYS);

        return dialogBox;
    }

    /**
     * Creates a dialog box for Kiki's response.
     *
     * @param message Response generated by Kiki.
     * @return A left-aligned Kiki dialog box.
     */
    public static DialogBox getKikiDialog(String message) {
        DialogBox dialogBox = new DialogBox(message, "Kiki", "kiki-avatar");
        dialogBox.setAlignment(Pos.TOP_LEFT);
        HBox.setHgrow(dialogBox.text, javafx.scene.layout.Priority.ALWAYS);

        return dialogBox;
    }
}
