package kiki.gui;

import javafx.beans.binding.Bindings;
import javafx.beans.property.ReadOnlyDoubleProperty;
import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;

/**
 * A chat bubble containing one message and a simple speaker badge.
 */
public class DialogBox extends HBox {
    private static final String ERROR_PREFIX = "OOPS!!!";
    private static final double MIN_MESSAGE_WIDTH = 120;
    private static final double MAX_MESSAGE_WIDTH = 520;
    private static final double NON_MESSAGE_WIDTH = 50;
    private static final double MESSAGE_WIDTH_RATIO = 0.82;

    private final Label text;
    private final Label avatar;

    private DialogBox(String message, String speaker, String styleClass) {
        text = new Label(message);
        avatar = new Label(speaker);

        text.setWrapText(true);
        text.getStyleClass().add("message-bubble");
        avatar.getStyleClass().addAll("speaker-label", styleClass);
        setSpacing(8);
        getChildren().addAll(avatar, text);
    }

    /**
     * Creates a dialog box for the user's message.
     *
     * @param message Message typed by the user.
     * @return A right-aligned user dialog box.
     */
    public static DialogBox getUserDialog(String message) {
        DialogBox dialogBox = new DialogBox(message, "You", "user-avatar");
        dialogBox.text.getStyleClass().add("user-message-bubble");
        dialogBox.setAlignment(Pos.TOP_RIGHT);
        dialogBox.getChildren().setAll(dialogBox.text, dialogBox.avatar);
        HBox.setHgrow(dialogBox.text, Priority.ALWAYS);

        return dialogBox;
    }

    /**
     * Creates a dialog box for Kiki's response.
     *
     * @param message Response generated by Kiki.
     * @return A left-aligned Kiki dialog box.
     */
    public static DialogBox getKikiDialog(String message) {
        DialogBox dialogBox = new DialogBox(message, "Kiki", "kiki-avatar");
        dialogBox.setAlignment(Pos.TOP_LEFT);
        HBox.setHgrow(dialogBox.text, Priority.ALWAYS);

        if (isErrorResponse(message)) {
            dialogBox.text.getStyleClass().add("error-message");
        }

        return dialogBox;
    }

    static boolean isErrorResponse(String response) {
        return response.startsWith(ERROR_PREFIX);
    }

    void bindMessageWidth(ReadOnlyDoubleProperty containerWidth) {
        text.maxWidthProperty().bind(Bindings.createDoubleBinding(
                () -> getMessageMaxWidth(containerWidth.get()), containerWidth));
    }

    static double getMessageMaxWidth(double containerWidth) {
        double availableWidth = (containerWidth - NON_MESSAGE_WIDTH) * MESSAGE_WIDTH_RATIO;
        return Math.max(MIN_MESSAGE_WIDTH, Math.min(MAX_MESSAGE_WIDTH, availableWidth));
    }
}
