package kiki.gui;

import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;

/**
 * A chat bubble containing one message and a simple speaker badge.
 */
public class DialogBox extends HBox {
    private static final String ERROR_PREFIX = "OOPS!!!";

    private final Label text;
    private final Label avatar;

    private DialogBox(String message, String speaker, String styleClass) {
        text = new Label(message);
        avatar = new Label(speaker);

        text.setWrapText(true);
        text.getStyleClass().add("message-bubble");
        text.maxWidthProperty().bind(widthProperty().subtract(42).multiply(0.82));
        avatar.getStyleClass().addAll("speaker-label", styleClass);
        setSpacing(8);
        getChildren().addAll(avatar, text);
    }

    /**
     * Creates a dialog box for the user's message.
     *
     * @param message Message typed by the user.
     * @return A right-aligned user dialog box.
     */
    public static DialogBox getUserDialog(String message) {
        DialogBox dialogBox = new DialogBox(message, "You", "user-avatar");
        dialogBox.text.getStyleClass().add("user-message-bubble");
        dialogBox.setAlignment(Pos.TOP_RIGHT);
        dialogBox.getChildren().setAll(dialogBox.text, dialogBox.avatar);

        return dialogBox;
    }

    /**
     * Creates a dialog box for Kiki's response.
     *
     * @param message Response generated by Kiki.
     * @return A left-aligned Kiki dialog box.
     */
    public static DialogBox getKikiDialog(String message) {
        DialogBox dialogBox = new DialogBox(message, "Kiki", "kiki-avatar");
        dialogBox.setAlignment(Pos.TOP_LEFT);

        if (isErrorResponse(message)) {
            dialogBox.text.getStyleClass().add("error-message");
        }

        return dialogBox;
    }

    static boolean isErrorResponse(String response) {
        return response.startsWith(ERROR_PREFIX);
    }
}
